title: Data Structures and Algorithms Fall 2023
description: Data Structures and Algorithms Course @ Sharif University of Technology
theme: just-the-docs

url: https://dsacourse.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
